/**
 * Derived GlideRecord method sets. The versioned table lives in `manifest.ts`.
 */

export {
  GLIDE_API_RELEASE,
  GLIDE_BULK_METHODS,
  GLIDE_CURSOR_ADVANCERS,
  GLIDE_FILTER_METHODS,
  GLIDE_KNOWN_METHODS,
  GLIDE_QUERY_EXECUTORS,
  GLIDE_QUERY_MODIFIERS,
  GLIDE_RESULT_CONSUMERS,
  GLIDE_SCOPED_RECORD_EVIDENCE,
  GLIDE_SYSTEM_BYPASS_METHODS,
  GLIDE_VALUE_EXTRACTORS,
} from "./manifest.js";
