// Writes src/version.ts from package.json so PACKAGE_VERSION is a static
// constant instead of a module-load filesystem read (FINDINGS.md MNT-002).
// Runs as npm prebuild; the committed file is asserted against package.json
// by tests/plugin.test.ts.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { readJson } from "./lib/json-artifact.mjs";
import { root } from "./lib/repo.mjs";

const { version } = readJson(join(root, "package.json"));
const source = `/* Generated by scripts/generate-version.mjs. Do not edit. */\nexport const PACKAGE_VERSION = ${JSON.stringify(version)};\n`;
writeFileSync(join(root, "src/version.ts"), source);
console.log(`src/version.ts = ${version}`);
