// Writes src/version.ts from package.json so PACKAGE_VERSION is a static
// constant instead of a module-load filesystem read (FINDINGS.md MNT-002).
// Runs as npm prebuild; the committed file is asserted against package.json
// by tests/plugin.test.ts.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const source = `/* Generated by scripts/generate-version.mjs. Do not edit. */\nexport const PACKAGE_VERSION = ${JSON.stringify(version)};\n`;
writeFileSync(join(root, "src/version.ts"), source);
console.log(`src/version.ts = ${version}`);
